spring:
  datasource:
    url: 'jdbc:mysql://114.215.159.226/shop'
    username: 'root'
    password: '931011'
    driver-class-name: 'com.mysql.jdbc.Driver'

  jedis:
    pool:
      host: '114.215.159.226'
      port: 6379
      password: 'letingoo'
      timeout: 0
      config:
        maxTotal: 100
        maxIdle: 10
        maxWaitMills: 10000
  aop:
    proxy-target-class: true

